when:
  - event: push

steps:
  - name: lint
    image: silkeh/clang
    commands:
      - make lint

  - name: clang-error-hell
    image: silkeh/clang
    commands:
      - make ERROR_HELL=1
  
  - name: clang
    image: silkeh/clang
    commands:
      - make
  
  - name: gcc-15
    image: gcc:15
    commands:
      - make CC=gcc
  
  - name: gcc-14
    image: gcc:14
    commands:
      - make CC=gcc
  
  - name: gcc-13
    image: gcc:13
    commands:
      - make CC=gcc
  
  - name: gcc-12
    image: gcc:12
    commands:
      - make CC=gcc