when:
  - event: push

steps:
#   removing the linter for now since clang-tidy works strangely in the docker image
#   - name: lint
#     image: silkeh/clang
#     commands:
#       - make lint

  - name: build
    image: silkeh/clang
    commands:
      - make