when:
  - event: push

steps:
  - name: lint
    image: debian
    commands:
      - apt-get -y update
      - apt-get -y upgrade
      - apt-get -y install make clang-tidy
      - make check

  - name: build
    image: silkeh/clang
    commands:
      - make